apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox-replicaset # Name of the ReplicaSet
  labels:
    app: busyBox # Label to identify the application
    tier: backend # Label to identify the tier of the application
spec:
  replicas: 5 # Number of pod replicas to maintain
  selector:
    matchLabels:
      env: development # Selector to match pods with this label
  template:
    metadata:
     name: busybox # Name of the pod
     labels:
        env: development # Label to identify the environment
        tier: backend # Label to identify the tier of the application
    spec:
      containers:
        - name: busybox # Name of the container
          image: busybox # Docker image to use for the container
          command: [ "sleep", "3600" ] # Command to run inside the container
